### PR TITLE
Added Ruby 2.3.0 and 2.4.1 to Travis configuration and removed 1.9.3

### PR DESCRIPTION
**Pull request by portertech**
Related to https://github.com/sensu-plugins/sensu-plugins-feature-requests/issues/27

### CODE REVIEW

**Comment by portertech** [comment]
@majormoses seems we need to remove support for 1.9?

**Comment by majormoses** [comment]
@portertech yup these repos have lots of cruft that we are slowly trying to clean up. As discussed I am not opposed to breaking changes like this as long as it is called out and versioned appropriately. I started updating this to reflect out stance on ruby version support which is essentially `!ruby_version.eol?`: https://github.com/sensu-plugins/documentation/pull/11

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
@portertech hey looks like you missed the important part of removing 1.9 support: https://github.com/sensu-plugins/sensu-plugins-execute/commit/67e0f13bc7d74f2c048d92fd821d36bde5c76b08#diff-03950be6b341adfeb7af5c138763a1d6R32 I released it as 1.0.1 as 1.0.0 when I merged it due to the gemspec not satisfying the runtime requirements to build it did not want to deploy in travis and I am not sure there is enough value for me to figure out how to release this manually.

released: https://rubygems.org/gems/sensu-plugins-execute/versions/1.0.1

**Pull request merged**
